#pragma once

#include "Imports/glew/include/GL/glew.h"
#include "Imports/glfw/include/GLFW/glfw3.h"
#include <iostream>
#include <cstring>
#include <functional>
#include <unordered_set>
#include <memory>
#include <vector>
#include <array>
#include <thread>
#include "FlatFoxRenderWarnings.hpp"
#include "Imports/glm/glm.hpp"
#include "Imports/glm/gtc/matrix_transform.hpp"
#include "Imports/stb_image/stb_image.h"
#include "VertexArray.hpp"
#include "VertexBuffer.hpp"
#include "VertexBufferLayout.hpp"
#include "Texture.hpp"
#include "IndexBuffer.hpp"
#include "Shader.hpp"
#include "Renderer.hpp"
#include "SimpleObject.hpp"
#include "SimpleWorld.hpp"
#include "SimplePhysics.hpp"
#include "SimplePhysicsObjects.hpp"
#include "Camera.hpp"
#include "FrameBufferObject.hpp"
#include "FlatFoxWindow.hpp"
